import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "./component/Header";
import Footer from "./component/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {
          process.env.NODE_ENV === "production" && (
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3653533988594535"
              crossOrigin="anonymous"></script>
          )
        }
      </head>
      <body className={`bg-gray-800`}>
        <NavigationMenuDemo />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
